name: Feature Request
description: Suggest an idea or enhancement for Tez
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I think Tez should...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also thought about...

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Who would benefit from this feature and how?
      placeholder: |
        - Embedded developers could...
        - Educational projects could...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my use case
        - Critical - blocking my work
    validations:
      required: true

  - type: dropdown
    id: roadmap
    attributes:
      label: Roadmap Alignment
      description: Does this align with existing roadmap phases?
      options:
        - Phase 2 (TLS/SSL, compression, config)
        - Phase 3 (HTTP/2, WebSocket, rate limiting)
        - Phase 4 (plugins, hot reload)
        - New/Not in roadmap
        - Not sure
    validations:
      required: false

  - type: dropdown
    id: willing-to-help
    attributes:
      label: Willing to Contribute?
      description: Would you be willing to help implement this?
      options:
        - "Yes, I can implement this"
        - "Yes, with guidance"
        - "Maybe, depends on complexity"
        - "No, but I can test it"
        - "No, just suggesting"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
      placeholder: Here's an example from another project...

  - type: checkboxes
    id: search
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've done the following
      options:
        - label: I searched existing issues and didn't find a duplicate
          required: true
        - label: This feature aligns with Tez's goals (educational/embedded focus)
          required: true
        - label: I've provided clear use cases
          required: true
